namespace BTCeApi
{
    public enum Pair
    {
        btc_usd,
        btc_rur,
        btc_eur,
        btc_cnh,
        btc_gbp,
        ltc_btc,
        ltc_usd,
        ltc_rur,
        ltc_eur,
        ltc_cnh,
        ltc_gbp,
        nmc_btc,
        nmc_usd,
        nvc_btc,
        nvc_usd,
        usd_rur,
        eur_usd,
        eur_rur,
        usd_cnh,
        gbp_usd,
        trc_btc,
        ppc_btc,
        ppc_usd,
        ftc_btc,
        xpm_btc,
        All
    }
}
